export interface PortfolioItem {
  id: number
  title: string
  businessType: string
  url: string
  imageUrl: string
  category: string
  desktopVideoUrl?: string
  mobileVideoUrl?: string
  description?: string
  serviceType?: string
  ranking?: string
}

export const portfolioData: PortfolioItem[] = [
  // Education
  {
    id: 1,
    title: "Arabic Guru Academy",
    businessType: "Education",
    url: "#",
    imageUrl: "/image/images/webeside-technology-lms-learning-management.webp",
    category: "Education",
    serviceType: "Enquiry",
    desktopVideoUrl: "https://youtu.be/YXCOJVW_xXU",
    mobileVideoUrl: "https://youtube.com/shorts/cJfp7JDg0bE",
    description: "This is a Dubai based project to provide quality education to the students.",
  },
  {
    id: 2,
    title: "Nextskilledge Academy",
    businessType: "Education",
    url: "#",
    imageUrl: "/image/images/webeside-technology-lms-learning-management.webp",
    category: "Education",
    serviceType: "Enquiry",
    desktopVideoUrl: "https://youtu.be/G-T02pBIvYk",
    mobileVideoUrl: "https://youtube.com/shorts/CE_pLJZLkiE",
    description: "This is an India, US & UK based PhD degree admission support and skill training platform.",
  },
  {
    id: 3,
    title: "Career 4s",
    businessType: "Education",
    url: "#",
    imageUrl: "/image/images/webeside-technology-lms-learning-management.webp",
    category: "Education",
    serviceType: "Enquiry",
    desktopVideoUrl: "https://youtu.be/yDhAajvg5uA",
    mobileVideoUrl: "https://youtube.com/shorts/xs5JzjTIfYQ",
    description: "This is a Delhi & Faridabad based College admission support and skill training platform.",
  },
  {
    id: 4,
    title: "The academic helper",
    businessType: "Education",
    url: "#",
    imageUrl: "/image/images/webeside-technology-lms-learning-management.webp",
    category: "Education",
    serviceType: "Enquiry",
    desktopVideoUrl: "https://youtu.be/urwkdfBKnJA",
    mobileVideoUrl: "https://youtube.com/shorts/YnTyovfU6ik",
    description: "It is a top academic support provider in Faridabad dealing with foreign university students.",
    ranking: "High",
  },
  {
    id: 5,
    title: "Skill For Career Academy",
    businessType: "Education",
    url: "#",
    imageUrl: "/image/images/webeside-technology-lms-learning-management.webp",
    category: "Education",
    serviceType: "Booking",
    desktopVideoUrl: "https://youtu.be/a8X4WylLzCU",
    mobileVideoUrl: "https://youtu.be/xZfG6Ks-dsM",
    description: "This is an India based premium online and offline skill training platform providing top courses.",
    ranking: "High",
  },
  {
    id: 6,
    title: "Skill For Career Institute",
    businessType: "Education",
    url: "#",
    imageUrl: "/image/images/webeside-technology-lms-learning-management.webp",
    category: "Education",
    serviceType: "Booking",
    desktopVideoUrl: "https://youtu.be/6o7Euin0qRA",
    mobileVideoUrl: "https://youtube.com/shorts/5JihiIPcP2M",
    description: "This is an India based premium online and offline skill training platform providing top courses.",
    ranking: "High",
  },
  // Real Estate
  {
    id: 7,
    title: "Darpann Investments",
    businessType: "Real Estate",
    url: "#",
    imageUrl: "/image/images/webeside-technology-showcase-demo.webp",
    category: "Real Estate",
    serviceType: "Enquiry",
    desktopVideoUrl: "https://youtu.be/5swn3fc3Bu4",
    mobileVideoUrl: "https://youtube.com/shorts/TJ244CSC81A",
    description: "This is a Gurgaon based real estate company providing investment opportunities in realty sector.",
  },
  {
    id: 8,
    title: "Naugaonfarmhouses",
    businessType: "Real Estate",
    url: "#",
    imageUrl: "/image/images/webeside-technology-showcase-demo.webp",
    category: "Real Estate",
    serviceType: "Enquiry",
    desktopVideoUrl: "https://youtu.be/1DsFKPHLj8g",
    mobileVideoUrl: "https://youtube.com/shorts/h8Sc8XcaSLw",
    description:
      "This is a Gurgaon & Rajasthan based real estate company providing investment opportunities in realty sector.",
  },
  {
    id: 9,
    title: "Goa Plot",
    businessType: "Real Estate",
    url: "#",
    imageUrl: "/image/images/webeside-technology-showcase-demo.webp",
    category: "Real Estate",
    serviceType: "Enquiry",
    desktopVideoUrl: "https://youtu.be/eimmxOnNtTQ",
    mobileVideoUrl: "https://youtube.com/shorts/t37RK93VSzE",
    description:
      "This is a Gurgaon & Goa based real estate company providing investment opportunities in realty sector.",
  },
  {
    id: 10,
    title: "Pinaki Infratech",
    businessType: "Real Estate",
    url: "#",
    imageUrl: "/image/images/webeside-technology-showcase-demo.webp",
    category: "Real Estate",
    serviceType: "Enquiry",
    desktopVideoUrl: "https://youtu.be/7RbSIlqdSZ8",
    mobileVideoUrl: "https://youtube.com/shorts/8QmPkpHJ9oY",
    description: "This is a NCR based real estate company providing investment opportunities in realty sector.",
    ranking: "High",
  },
  {
    id: 11,
    title: "Velvet Vista",
    businessType: "Real Estate",
    url: "#",
    imageUrl: "/image/images/webeside-technology-showcase-demo.webp",
    category: "Real Estate",
    serviceType: "Enquiry",
    desktopVideoUrl: "https://youtu.be/d3W0atDPZok",
    mobileVideoUrl: "https://youtube.com/shorts/5i_bN75Y3gM",
    description: "This is a Gurgaon based real estate company providing investment opportunities in realty sector.",
    ranking: "High",
  },
  {
    id: 12,
    title: "Gurgaon Best Properties",
    businessType: "Real Estate",
    url: "#",
    imageUrl: "/image/images/webeside-technology-showcase-demo.webp",
    category: "Real Estate",
    serviceType: "Enquiry",
    desktopVideoUrl: "https://youtu.be/aamWUFyiPV8",
    mobileVideoUrl: "https://youtube.com/shorts/CAchirlLd0Y",
    description: "This is a Gurgaon based real estate company providing investment opportunities in realty sector.",
    ranking: "High",
  },
  {
    id: 13,
    title: "Nature Meadows",
    businessType: "Real Estate",
    url: "#",
    imageUrl: "/image/images/webeside-technology-showcase-demo.webp",
    category: "Real Estate",
    serviceType: "Enquiry",
    desktopVideoUrl: "https://youtu.be/9FOjRebSfCk",
    mobileVideoUrl: "https://youtube.com/shorts/RHxW0Bcuo7o",
    description: "It is a real estate networking website based in Noida connecting all real estate dealers.",
    ranking: "High",
  },
  // Healthcare
  {
    id: 14,
    title: "Darshana Weightloss Coach",
    businessType: "Healthcare",
    url: "#",
    imageUrl: "/image/images/webeside-technology-showcase-demo.webp",
    category: "Healthcare",
    serviceType: "Enquiry",
    desktopVideoUrl: "https://youtu.be/cOuTq3VlKTw",
    mobileVideoUrl: "https://youtube.com/shorts/XhDtwhDfu2k",
    description: "This is a Gurgaon based weight loss coach to guide and coach you on health issues.",
  },
  {
    id: 15,
    title: "Albadrcure",
    businessType: "Healthcare",
    url: "#",
    imageUrl: "/image/images/webeside-technology-showcase-demo.webp",
    category: "Healthcare",
    serviceType: "Enquiry",
    desktopVideoUrl: "https://youtu.be/e1KOo6n1_Eg",
    mobileVideoUrl: "https://youtube.com/shorts/fVyM5TAC0ms",
    description: "Top medical tourism company in Dubai, ranks in top results on google.",
  },
  {
    id: 16,
    title: "The Skin Recovery Clinic",
    businessType: "Healthcare",
    url: "#",
    imageUrl: "/image/images/webeside-technology-showcase-demo.webp",
    category: "Healthcare",
    serviceType: "Enquiry",
    desktopVideoUrl: "https://youtu.be/EA2ar3usTaw",
    mobileVideoUrl: "https://youtube.com/shorts/QpkPRAEgs3A",
    description:
      "It is a skin recovery clinic website ranking top on google for the people looking for skin treatment.",
    ranking: "High",
  },
  {
    id: 17,
    title: "Rohtak Surgical Corporation",
    businessType: "Healthcare",
    url: "#",
    imageUrl: "/image/images/webeside-technology-showcase-demo.webp",
    category: "Healthcare",
    serviceType: "Enquiry",
    desktopVideoUrl: "https://youtu.be/PtcbM0W2XhA",
    mobileVideoUrl: "https://youtube.com/shorts/K1WIhJneLy8",
    description: "This is a premium medical equipment supplier brand platform based in India.",
  },
  // Manufacturing
  {
    id: 18,
    title: "Nirmal Packaging",
    businessType: "Manufacturing",
    url: "#",
    imageUrl: "/image/images/webeside-technology-showcase-demo.webp",
    category: "Manufacturing",
    serviceType: "Enquiry",
    desktopVideoUrl: "https://youtu.be/YVSlr7QW9wc",
    mobileVideoUrl: "https://youtube.com/shorts/r-VCUth6GA0",
    description: "Packaging material manufacturing Solution in Faridabad and ranks on top.",
  },
  {
    id: 19,
    title: "Industrial Innovations",
    businessType: "Manufacturing",
    url: "#",
    imageUrl: "/image/images/webeside-technology-showcase-demo.webp",
    category: "Manufacturing",
    serviceType: "Enquiry",
    desktopVideoUrl: "https://youtu.be/tBvqpEjRUIs",
    mobileVideoUrl: "https://youtube.com/shorts/vuRvTN_bT0c",
    description: "Top Lubricating Industrial machinery manufacturer in Faridabad.",
  },
  {
    id: 20,
    title: "Farahpaper product",
    businessType: "Manufacturing",
    url: "#",
    imageUrl: "/image/images/webeside-technology-showcase-demo.webp",
    category: "Manufacturing",
    serviceType: "Enquiry",
    desktopVideoUrl: "https://youtu.be/3nzPtdZFeVc",
    mobileVideoUrl: "https://youtube.com/shorts/evt_DlNodLc",
    description: "It is an India based paper manufacturer company dealing in different paper items.",
  },
  {
    id: 21,
    title: "Hindustan General Metal",
    businessType: "Manufacturing",
    url: "#",
    imageUrl: "/image/images/webeside-technology-showcase-demo.webp",
    category: "Manufacturing",
    serviceType: "Enquiry",
    desktopVideoUrl: "https://youtu.be/ksquTPDRuLA",
    mobileVideoUrl: "https://youtube.com/shorts/K_Hh15HMoC8",
    description: "It is a steel product selling and manufacturing website ranking high on google.",
    ranking: "High",
  },
  // Electronics
  {
    id: 22,
    title: "24by7 Service Center",
    businessType: "Electronics",
    url: "#",
    imageUrl: "/image/images/webeside-technology-showcase-demo.webp",
    category: "Electronics",
    serviceType: "Enquiry",
    desktopVideoUrl: "https://youtu.be/KNk1ig45kHM",
    mobileVideoUrl: "https://youtube.com/shorts/hUfIp1VQ250",
    description: "Popular electronic service & repair centre in Faridabad.",
  },
  {
    id: 23,
    title: "Aarav AC Wala",
    businessType: "Electronics",
    url: "#",
    imageUrl: "/image/images/webeside-technology-showcase-demo.webp",
    category: "Electronics",
    serviceType: "Enquiry",
    desktopVideoUrl: "https://youtu.be/uMki_OABedY",
    mobileVideoUrl: "https://youtube.com/shorts/dnpY0oZzlyQ",
    description: "Its a Faridabad based newly started repair service provider landing page for ads.",
    ranking: "High",
  },
  {
    id: 24,
    title: "Wextou",
    businessType: "Electronics",
    url: "#",
    imageUrl: "/image/images/webeside-technology-showcase-demo.webp",
    category: "Electronics",
    serviceType: "Enquiry",
    desktopVideoUrl: "https://youtu.be/4AiCxhtYRHE",
    mobileVideoUrl: "https://youtube.com/shorts/-p9TA1Nf1ds",
    description: "Its an enquiry based website of a security systems providers based in India.",
  },
  {
    id: 25,
    title: "Mepl Sky",
    businessType: "Electronics",
    url: "#",
    imageUrl: "/image/images/webeside-technology-showcase-demo.webp",
    category: "Electronics",
    serviceType: "Enquiry",
    desktopVideoUrl: "https://youtu.be/_iqv5u5RyNc",
    mobileVideoUrl: "https://youtube.com/shorts/TwTBsuLiZdw",
    description: "Its an enquiry based website of a electronic products dealer based in India.",
  },
  // Tour and Travel
  {
    id: 26,
    title: "Limousine Rental Service",
    businessType: "Tour and Travel",
    url: "#",
    imageUrl: "/image/images/webeside-technology-showcase-demo.webp",
    category: "Tour and Travel",
    serviceType: "Booking",
    desktopVideoUrl: "https://youtu.be/BPLLNze6Ro0",
    description: "Its a US based premium transport through cab Service ranks top on the google in US.",
    ranking: "High",
  },
  {
    id: 27,
    title: "True Love Holidays",
    businessType: "Tour and Travel",
    url: "#",
    imageUrl: "/image/images/webeside-technology-showcase-demo.webp",
    category: "Tour and Travel",
    serviceType: "Enquiry",
    desktopVideoUrl: "https://youtu.be/11GgMkSZlv4",
    mobileVideoUrl: "https://youtube.com/shorts/AbWaQ69_V6c",
    description: "This is a Punjab based Tour and travel booking enquiry platform for all.",
    ranking: "High",
  },
  {
    id: 28,
    title: "Sunshine cab rental",
    businessType: "Tour and Travel",
    url: "#",
    imageUrl: "/image/images/webeside-technology-showcase-demo.webp",
    category: "Tour and Travel",
    serviceType: "Enquiry",
    desktopVideoUrl: "https://youtu.be/0Gp6PhGBmQw",
    mobileVideoUrl: "https://youtube.com/shorts/LAw9oZOYcwI",
    description: "It is a top local cab service provider company having a landing page for enquiries.",
    ranking: "High",
  },
  {
    id: 29,
    title: "The Pinus Resort",
    businessType: "Tour and Travel",
    url: "#",
    imageUrl: "/image/images/webeside-technology-showcase-demo.webp",
    category: "Tour and Travel",
    serviceType: "Enquiry",
    desktopVideoUrl: "https://youtu.be/DSp4CgMiM38",
    description: "It is a resort booking enquiry website for premium resorts in the montains.",
  },
  {
    id: 30,
    title: "Tourist Leader",
    businessType: "Tour and Travel",
    url: "#",
    imageUrl: "/image/images/webeside-technology-showcase-demo.webp",
    category: "Tour and Travel",
    serviceType: "Booking",
    desktopVideoUrl: "https://youtu.be/ZmpfSfi8ILU",
    mobileVideoUrl: "https://youtube.com/shorts/jv0rNKqHzs0",
    description: "It is a premium travel and flight booking website based in Bangalore and Vietnam.",
    ranking: "High",
  },
  // Astrology
  {
    id: 31,
    title: "Nmastu",
    businessType: "Astrology",
    url: "#",
    imageUrl: "/image/images/webeside-technology-showcase-demo.webp",
    category: "Astrology",
    serviceType: "Enquiry",
    desktopVideoUrl: "https://youtu.be/X_dxfqyBwbM",
    mobileVideoUrl: "https://youtube.com/shorts/DB4j6TGkKYI",
    description: "Its a Delhi based popular astrologer works with top Indian celebrity superstars.",
    ranking: "High",
  },
  // Banking & Finance
  {
    id: 32,
    title: "Lex Setu Pvt Ltd",
    businessType: "Accounting",
    url: "#",
    imageUrl: "/image/images/webeside-technology-showcase-demo.webp",
    category: "Banking & Finance",
    serviceType: "Enquiry",
    desktopVideoUrl: "https://youtu.be/UE21Rg3iyJY",
    mobileVideoUrl: "https://youtube.com/shorts/i-aTQbr4o_8",
    description: "It is Delhi based top CA service website which is designed simple yet beautiful.",
    ranking: "High",
  },
  {
    id: 33,
    title: "Paisa Samadhan",
    businessType: "Banking & Finance",
    url: "#",
    imageUrl: "/image/images/webeside-technology-showcase-demo.webp",
    category: "Banking & Finance",
    serviceType: "Enquiry",
    desktopVideoUrl: "https://youtu.be/DngSfFD7AGY",
    mobileVideoUrl: "https://youtube.com/shorts/k3AbOzhQeBg",
    description: "It is a financial service provider company in India, deals in insurance qne loan facilities.",
    ranking: "High",
  },
  // Ecommerce
  {
    id: 34,
    title: "Everlywhite",
    businessType: "Ecommerce",
    url: "#",
    imageUrl: "/image/images/webeside-technology-showcase-demo.webp",
    category: "Ecommerce",
    serviceType: "Ecommerce",
    desktopVideoUrl: "https://youtu.be/Rxzt0_fxyVY",
    mobileVideoUrl: "https://youtube.com/shorts/3mI4JdemlXY",
    description: "This is a premium art & craft ecommerce platform based in North eastern part of India.",
  },
  {
    id: 35,
    title: "Until Nature",
    businessType: "Ecommerce",
    url: "#",
    imageUrl: "/image/images/webeside-technology-showcase-demo.webp",
    category: "Ecommerce",
    serviceType: "Ecommerce",
    desktopVideoUrl: "https://youtu.be/TUx7iTgeIh8",
    mobileVideoUrl: "https://youtube.com/shorts/NiOf2tQhN_Y",
    description: "This is a nature based daily essentials ecommerce platform based in Bangalore, India.",
  },
  {
    id: 36,
    title: "Casa Organix",
    businessType: "Ecommerce",
    url: "#",
    imageUrl: "/image/images/webeside-technology-showcase-demo.webp",
    category: "Ecommerce",
    serviceType: "Ecommerce",
    desktopVideoUrl: "https://youtu.be/GYKAiSX4fqc",
    mobileVideoUrl: "https://youtube.com/shorts/Sf70bBL34Og",
    description: "This is a Medical apparel ecommerce brand platform based in USA and India.",
  },
  {
    id: 37,
    title: "Toy On rent",
    businessType: "Ecommerce",
    url: "#",
    imageUrl: "/image/images/webeside-technology-showcase-demo.webp",
    category: "Ecommerce",
    serviceType: "Ecommerce",
    desktopVideoUrl: "https://youtu.be/BM8EPzprtNw",
    mobileVideoUrl: "https://youtube.com/shorts/Q8pZFlh5rQI",
    description: "This is a toy rental ecommerce brand platform based in Bihar, India.",
  },
  {
    id: 38,
    title: "Barraid",
    businessType: "Food and Beverages",
    url: "#",
    imageUrl: "/image/images/webeside-technology-showcase-demo.webp",
    category: "Ecommerce",
    serviceType: "Ecommerce",
    desktopVideoUrl: "https://youtu.be/sb34aHYLg1U",
    mobileVideoUrl: "https://youtube.com/shorts/fpRpkQ-aDcc",
    description: "It is a premium beer dispenser dealer working in india through ecommerce website.",
  },
  // Interior
  {
    id: 39,
    title: "Delight Windows",
    businessType: "Interior",
    url: "#",
    imageUrl: "/image/images/webeside-technology-showcase-demo.webp",
    category: "Interior",
    serviceType: "Enquiry",
    desktopVideoUrl: "https://youtu.be/TKab8o92MCM",
    mobileVideoUrl: "https://youtube.com/shorts/RbwapRhJ7y0",
    description: "It is a Gurgaon based window and door solution platform which is very popular.",
    ranking: "High",
  },
  {
    id: 40,
    title: "Homspace",
    businessType: "Interior",
    url: "#",
    imageUrl: "/image/images/webeside-technology-showcase-demo.webp",
    category: "Interior",
    serviceType: "Enquiry",
    desktopVideoUrl: "https://youtu.be/chPFSDafxeU",
    description: "Its an enquiry based website providing premium interior design services in India.",
  },
  // NGO
  {
    id: 41,
    title: "SSS Bharat",
    businessType: "NGO",
    url: "#",
    imageUrl: "/image/images/webeside-technology-showcase-demo.webp",
    category: "NGO",
    serviceType: "Enquiry",
    desktopVideoUrl: "https://youtu.be/gFhJaE-5LA8",
    mobileVideoUrl: "https://youtube.com/shorts/LdVl11KOe8I",
    description: "It is an NGO based in Faridabad showcasing their work theough their website.",
  },
  // Art & Entertainment
  {
    id: 42,
    title: "Join Bollywood",
    businessType: "Art & Entertainment",
    url: "#",
    imageUrl: "/image/images/webeside-technology-showcase-demo.webp",
    category: "Art & Entertainment",
    serviceType: "Enquiry",
    desktopVideoUrl: "https://youtu.be/syynt1JeW9U",
    mobileVideoUrl: "https://youtube.com/shorts/LEe-DAkziXQ",
    description: "This is an audition and interview for bollywood platform based in UP, India.",
  },
  // Skin & Beauty
  {
    id: 43,
    title: "AMIY Parlour",
    businessType: "Skin & Beauty",
    url: "#",
    imageUrl: "/image/images/webeside-technology-showcase-demo.webp",
    category: "Skin & Beauty",
    serviceType: "Enquiry",
    desktopVideoUrl: "https://youtu.be/_eSvL1cqrn4",
    mobileVideoUrl: "https://youtube.com/shorts/_nIsfX91yRA",
    description: "This is a premium parlour service provider in India ranking on top of google.",
    ranking: "High",
  },
  {
    id: 44,
    title: "HQ Beauty Parlour, USA",
    businessType: "Skin & Beauty",
    url: "#",
    imageUrl: "/image/images/webeside-technology-showcase-demo.webp",
    category: "Skin & Beauty",
    serviceType: "Enquiry",
    desktopVideoUrl: "https://youtu.be/_kVHY_dc2FU",
    mobileVideoUrl: "https://youtube.com/shorts/u51lZTpeKdM",
    description: "This is a premium parlour service provider in USA ranking on top of google.",
    ranking: "High",
  },
  // Other Service
  {
    id: 45,
    title: "Print Outs Wala",
    businessType: "Other Service",
    url: "#",
    imageUrl: "/image/images/webeside-technology-showcase-demo.webp",
    category: "Other Service",
    serviceType: "Ecommerce",
    desktopVideoUrl: "https://youtu.be/hBKZMl8JGzM",
    mobileVideoUrl: "https://youtube.com/shorts/aHU51CFYCqk",
    description: "This is a website for a premium photo copy service provider in Faridabad.",
  },
  {
    id: 46,
    title: "Print Kaya",
    businessType: "Other Service",
    url: "#",
    imageUrl: "/image/images/webeside-technology-showcase-demo.webp",
    category: "Other Service",
    serviceType: "Ecommerce",
    desktopVideoUrl: "https://youtu.be/UZgizCtZ9Oc",
    description: "This is a website for a premium material printing service provider in Faridabad.",
  },
]

export const categories = [
  "All",
  "Education",
  "Real Estate",
  "Healthcare",
  "Manufacturing",
  "Electronics",
  "Tour and Travel",
  "Astrology",
  "Banking & Finance",
  "Ecommerce",
  "Interior",
  "NGO",
  "Art & Entertainment",
  "Skin & Beauty",
  "Other Service",
]

export const videoPortfolioItems = portfolioData.filter((item) => item.desktopVideoUrl && item.mobileVideoUrl)

export const highRankedItems = portfolioData.filter((item) => item.ranking === "High")

export function getYouTubeEmbedUrl(url: string): string {
  if (!url) return ""

  const patterns = [
    /(?:youtube\.com\/watch\?v=|youtu\.be\/|youtube\.com\/embed\/)([^&\s]+)/,
    /youtube\.com\/shorts\/([^&\s]+)/,
  ]

  for (const pattern of patterns) {
    const match = url.match(pattern)
    if (match && match[1]) {
      return `https://www.youtube.com/embed/${match[1]}?autoplay=1&loop=1&playlist=${match[1]}&mute=1&controls=0&modestbranding=1&rel=0&showinfo=0`
    }
  }

  return ""
}
