export interface Service {
  id: number
  title: string
  description: string
  icon: string
  reactIcon?: string
  image: string
  features: string[]
}

export interface ServiceCategory {
  name: string
  icon: string
  reactIcon?: string
  services: Service[]
}

export const servicesData: ServiceCategory[] = [
  {
    name: "Digital Marketing",
    icon: "TrendingUp",
    reactIcon: "FaChartLine",
    services: [
      {
        id: 1,
        title: "Search Engine Optimization (SEO)",
        description:
          "Boost your website's visibility on search engines with data-driven SEO strategies and proven techniques.",
        icon: "Search",
        reactIcon: "FaSearchDollar",
        image: "/image/images/seo-analytics-dashboard.webp",
        features: ["Keyword Research", "On-page Optimization", "Technical SEO", "Link Building"],
      },
      {
        id: 2,
        title: "Pay-Per-Click Advertising (Google Ads / Meta Ads)",
        description: "Maximize ROI with targeted Google Ads and Meta Ads campaigns that drive qualified leads.",
        icon: "Target",
        reactIcon: "SiGoogleads",
        image: "/image/images/google-ads-facebook-ads-dashboard.webp",
        features: ["Google Ads Management", "Facebook Ads", "Instagram Ads", "ROI Tracking"],
      },
      {
        id: 3,
        title: "Social Media Marketing",
        description: "Build brand awareness and engage your audience across all major social media platforms.",
        icon: "Share2",
        reactIcon: "FaHashtag",
        image: "/image/images/social-media-marketing-content.webp",
        features: ["Content Strategy", "Platform Management", "Community Engagement", "Analytics"],
      },
      {
        id: 4,
        title: "Bulk WhatsApp Marketing",
        description: "Reach thousands of customers instantly with targeted WhatsApp campaigns and automated messaging.",
        icon: "MessageCircle",
        reactIcon: "FaWhatsapp",
        image: "/image/images/whatsapp-business-marketing.webp",
        features: ["Bulk Messaging", "Media Sharing", "Campaign Analytics", "Automated Responses"],
      },
      {
        id: 5,
        title: "Content Writing & Designing",
        description: "Professional content creation and creative designs that capture attention and drive engagement.",
        icon: "FileText",
        reactIcon: "FaPenFancy",
        image: "/image/images/content-writing-graphic-design.webp",
        features: ["Blog Writing", "Social Media Content", "Graphic Design", "Video Editing"],
      },
      {
        id: 6,
        title: "Affiliate / Referral Marketing",
        description: "Grow your business through strategic affiliate and referral marketing programs.",
        icon: "Users",
        reactIcon: "FaHandshake",
        image: "/image/images/affiliate-referral-marketing-network.webp",
        features: ["Affiliate Program Setup", "Partner Recruitment", "Commission Management", "Performance Tracking"],
      },
      {
        id: 7,
        title: "Google My Business (GMB) Optimization & Map Listing",
        description: "Optimize your local presence with GMB optimization and accurate business listings.",
        icon: "MapPin",
        reactIcon: "SiGooglemaps",
        image: "/image/google-my-business-maps-listing.webp",
        features: ["GMB Setup", "Local SEO", "Review Management", "Map Optimization"],
      },
      {
        id: 8,
        title: "Business Listing Services",
        description: "Get your business listed on top platforms like Amazon, Meesho, and more for maximum visibility.",
        icon: "Store",
        reactIcon: "FaAmazon",
        image: "/image/business-listing-amazon-meesho.webp",
        features: ["Amazon Listing", "Meesho Setup", "Multi-platform Management", "Product Optimization"],
      },
      {
        id: 9,
        title: "LinkedIn Marketing",
        description: "B2B marketing strategies on LinkedIn to connect with decision-makers and grow your network.",
        icon: "Briefcase",
        reactIcon: "FaLinkedin",
        image: "/image/images/linkedin-marketing-b2b.webp",
        features: ["Profile Optimization", "Lead Generation", "Content Strategy", "Connection Building"],
      },
      {
        id: 10,
        title: "Pinterest Marketing",
        description: "Drive traffic and sales with visually appealing Pinterest marketing campaigns.",
        icon: "Image",
        reactIcon: "FaPinterest",
        image: "/image/pinterest-marketing-visual.webp",
        features: ["Pin Design", "Board Management", "Pinterest SEO", "Analytics"],
      },
      {
        id: 11,
        title: "Photo & Video Shoots",
        description: "Professional photography and videography services for your marketing campaigns.",
        icon: "Camera",
        reactIcon: "FaCamera",
        image: "/image/images/content-writing-graphic-design.webp",
        features: ["Product Photography", "Corporate Videos", "Event Coverage", "Post-production"],
      },
      {
        id: 12,
        title: "PR & Influencer Marketing",
        description: "Amplify your brand through strategic PR campaigns and influencer partnerships.",
        icon: "Star",
        reactIcon: "FaBullhorn",
        image: "/image/pr-influencer-marketing.webp",
        features: ["Press Releases", "Influencer Outreach", "Campaign Management", "Media Relations"],
      },
    ],
  },
  {
    name: "Website & App Development",
    icon: "Code2",
    reactIcon: "FaCode",
    services: [
      {
        id: 13,
        title: "Enquiry Website & App Development",
        description: "Professional business websites and apps to showcase services and capture quality leads.",
        icon: "Layout",
        reactIcon: "FaGlobe",
        image: "/image/images_services/Website and App Development.webp",
        features: ["Responsive Design", "Contact Forms", "Lead Management", "Fast Loading"],
      },
      {
        id: 14,
        title: "E-commerce Website & App Development",
        description: "Complete online store solutions with payment gateways and inventory management.",
        icon: "ShoppingCart",
        reactIcon: "FaShoppingCart",
        image: "/image/images_services/Ecommerce webiste and App Development.webp",
        features: ["Product Catalog", "Payment Integration", "Order Management", "Admin Dashboard"],
      },
      {
        id: 15,
        title: "Booking Website & App Development",
        description:
          "Advanced booking systems for appointments, hotels, tours, and events with real-time availability.",
        icon: "Calendar",
        reactIcon: "FaCalendarCheck",
        image: "/image/images_services/Booking Website and App Development.webp",
        features: ["Real-time Availability", "Payment Processing", "Calendar Integration", "Reminders"],
      },
      {
        id: 16,
        title: "Rental Website & App Development",
        description: "Complete rental management platforms for vehicles, properties, and equipment.",
        icon: "Key",
        reactIcon: "FaKey",
        image: "/image/images_services/Rental website and app development.webp",
        features: ["Inventory Management", "Booking Calendar", "Payment Gateway", "User Dashboard"],
      },
      {
        id: 17,
        title: "Native & Hybrid App Development",
        description: "High-performance mobile apps for iOS and Android using native and cross-platform technologies.",
        icon: "Smartphone",
        reactIcon: "FaMobileAlt",
        image: "/image/images_services/Native Hybrid and App  development.webp",
        features: ["iOS & Android", "Cross-platform", "Native Performance", "App Store Submission"],
      },
      {
        id: 18,
        title: "Management Portal Development",
        description: "Custom management portals for businesses to streamline operations and workflows.",
        icon: "Monitor",
        reactIcon: "FaDesktop",
        image: "/image/images_services/Management Portal Development.webp",
        features: ["Admin Dashboard", "User Management", "Role-based Access", "Analytics"],
      },
      {
        id: 19,
        title: "API Integration Services",
        description: "Seamless integration with third-party services and custom API development for your applications.",
        icon: "Plug",
        reactIcon: "FaPlug",
        image: "/image/images_services/Api Integration Service.webp",
        features: ["Payment Gateways", "SMS & Email APIs", "Social Media APIs", "Custom APIs"],
      },
      {
        id: 20,
        title: "Website Maintenance",
        description: "Ongoing website maintenance and updates to keep your site secure and running smoothly.",
        icon: "Wrench",
        reactIcon: "FaWrench",
        image: "/image/images_services/Website Maintenance.webp",
        features: ["Regular Updates", "Bug Fixes", "Security Patches", "Performance Monitoring"],
      },
      {
        id: 21,
        title: "Website Optimization",
        description: "Improve website speed, performance, and user experience with comprehensive optimization.",
        icon: "Zap",
        reactIcon: "FaBolt",
        image: "/image/images_services/Website Optimization.webp",
        features: ["Speed Optimization", "SEO Enhancement", "Mobile Optimization", "Code Optimization"],
      },
      {
        id: 22,
        title: "Website Security Services",
        description: "Protect your website from cyber threats with advanced security measures and monitoring.",
        icon: "Shield",
        reactIcon: "FaShieldAlt",
        image: "/image/images_services/Website and App Development.webp",
        features: ["SSL Certificates", "Malware Scanning", "Firewall Setup", "Security Audits"],
      },
      {
        id: 23,
        title: "AI Chatbot Development",
        description: "Intelligent chatbots powered by AI for 24/7 customer support and engagement.",
        icon: "Bot",
        reactIcon: "FaRobot",
        image: "/image/images_services/AI chatbot development.webp",
        features: ["24/7 Availability", "Natural Language", "Multi-language", "CRM Integration"],
      },
      {
        id: 24,
        title: "Cloud Integration Services",
        description: "Seamless cloud integration for scalable and reliable application infrastructure.",
        icon: "Cloud",
        reactIcon: "FaCloud",
        image: "/image/images_services/Website and App Development.webp",
        features: ["AWS Integration", "Azure Services", "Cloud Migration", "DevOps Setup"],
      },
    ],
  },
  {
    name: "SaaS Services",
    icon: "Cloud",
    reactIcon: "FaCloudUploadAlt",
    services: [
      {
        id: 25,
        title: "Gym Management System (GMS)",
        description: "Complete gym management software with member tracking, billing, and attendance.",
        icon: "Dumbbell",
        reactIcon: "FaDumbbell",
        image: "/image/GYM Management System ( GMS ).webp",
        features: ["Member Management", "Billing & Invoicing", "Attendance Tracking", "Payment Integration"],
      },
      {
        id: 26,
        title: "HR Management System (HRMS)",
        description: "Comprehensive HRMS for employee management, payroll, attendance, and performance tracking.",
        icon: "Users",
        reactIcon: "FaUsers",
        image: "/image/Hr management System ( HRMS ).webp",
        features: ["Employee Records", "Payroll Processing", "Leave Management", "Performance Tracking"],
      },
      {
        id: 27,
        title: "E-commerce Website Solutions",
        description: "Ready-to-deploy e-commerce platforms with all essential features for online selling.",
        icon: "ShoppingBag",
        reactIcon: "FaShoppingBag",
        image: "/image/Ecommerce CMS Website Solution.webp",
        features: ["Product Management", "Order Processing", "Payment Gateway", "Inventory Tracking"],
      },
      {
        id: 28,
        title: "Service API Provider",
        description: "Custom API development and integration services for various business needs.",
        icon: "Webhook",
        reactIcon: "FaServer",
        image: "/image/Service API Provider.webp",
        features: ["RESTful APIs", "GraphQL", "Documentation", "Scalable Infrastructure"],
      },
      {
        id: 29,
        title: "Learning Management System (LMS)",
        description: "Advanced LMS platform for online courses, training, and educational content.",
        icon: "GraduationCap",
        reactIcon: "FaGraduationCap",
        image: "/image/Learning Management System.webp",
        features: ["Course Management", "Student Portal", "Assessments & Quizzes", "Progress Tracking"],
      },
      {
        id: 30,
        title: "CA / CS Knowledge Hub (SaaS Platform)",
        description: "Specialized platform for CA and CS professionals to manage clients and knowledge resources.",
        icon: "BookOpen",
        reactIcon: "FaBookOpen",
        image: "/image/CA CS knowledge Hub.webp",
        features: ["Client Management", "Document Repository", "Deadline Tracking", "Collaboration Tools"],
      },
      {
        id: 31,
        title: "Customer Management System (CMS)",
        description: "Powerful CRM to manage customer relationships, sales pipeline, and business growth.",
        icon: "UserCheck",
        reactIcon: "FaUserTie",
        image: "/image/Customer Relationship ( CRM &  CMS ).webp",
        features: ["Contact Management", "Sales Pipeline", "Task Automation", "Analytics & Reports"],
      },
      {
        id: 32,
        title: "Astrology Management System",
        description: "Specialized software for astrology consultations, horoscope generation, and client management.",
        icon: "Star",
        reactIcon: "FaStar",
        image: "/image/Astrology mnagement System.webp",
        features: ["Client Management", "Horoscope Generation", "Appointment Booking", "Payment Processing"],
      },
      {
        id: 33,
        title: "Native App Management Services",
        description: "Complete management services for native mobile applications including updates and support.",
        icon: "Smartphone",
        reactIcon: "FaMobile",
        image: "/image/Ai ChatBot Development and GYM Management System ( GMS ).webp",
        features: ["App Updates", "Bug Fixes", "Performance Monitoring", "User Support"],
      },
    ],
  },
  {
    name: "Designing Services",
    icon: "Palette",
    reactIcon: "FaPalette",
    services: [
      {
        id: 34,
        title: "Logo & Favicon Designing",
        description: "Memorable brand identities with professional logo and favicon designs that stand out.",
        icon: "Sparkles",
        reactIcon: "FaMagic",
        image: "/image/Logo & Favicon Designing Services.webp",
        features: ["Multiple Concepts", "Vector Files", "Brand Guidelines", "Unlimited Revisions"],
      },
      {
        id: 35,
        title: "Poster Designing",
        description: "Eye-catching poster designs for marketing campaigns, events, and promotions.",
        icon: "Image",
        reactIcon: "FaImage",
        image: "/image/Poster designing.webp",
        features: ["Custom Designs", "Print & Digital", "Multiple Sizes", "Fast Turnaround"],
      },
      {
        id: 36,
        title: "Banner Designing",
        description: "Professional banner designs for websites, social media, and advertising campaigns.",
        icon: "Layout",
        reactIcon: "FaRegImage",
        image: "/image/Banner Designing.webp",
        features: ["Web Banners", "Social Media Banners", "Animated Banners", "Print Banners"],
      },
      {
        id: 37,
        title: "Brochure Designing",
        description: "Professional brochure designs that effectively communicate your business offerings.",
        icon: "Book",
        reactIcon: "FaBook",
        image: "/image/Brochure Designing.webp",
        features: ["Bi-fold & Tri-fold", "Corporate Style", "Print-ready Files", "Content Writing"],
      },
      {
        id: 38,
        title: "Catalogue Designing",
        description: "Beautiful product catalogs that showcase your offerings in the best light.",
        icon: "BookOpen",
        reactIcon: "FaBookOpen",
        image: "/image/Catalogue Designing.webp",
        features: ["Product Layout", "High-quality Images", "Print & Digital", "Interactive PDFs"],
      },
      {
        id: 39,
        title: "Company Brochure Designing",
        description: "Corporate brochures that communicate your company's vision, mission, and values.",
        icon: "Briefcase",
        reactIcon: "FaBriefcase",
        image: "/image/Brochure Designing.webp",
        features: ["Corporate Identity", "Professional Layout", "High-quality Print", "Content Strategy"],
      },
      {
        id: 40,
        title: "Prospectus Designing",
        description: "Comprehensive prospectus designs for educational institutions and businesses.",
        icon: "FileText",
        reactIcon: "FaFileAlt",
        image: "/image/Prospectus Designing.webp",
        features: ["Detailed Layouts", "Information Design", "Print-ready Files", "Professional Finish"],
      },
      {
        id: 41,
        title: "Wedding Card Designing",
        description: "Beautiful custom wedding invitation designs for your special day.",
        icon: "Heart",
        reactIcon: "FaHeart",
        image: "/image/Wedding Card Designing.webp",
        features: ["Custom Themes", "Digital & Print", "RSVP Integration", "Multiple Formats"],
      },
      {
        id: 42,
        title: "UI / UX Designing",
        description: "User-centered interface designs that deliver exceptional user experiences.",
        icon: "Monitor",
        reactIcon: "FaFigma",
        image: "/image/Ui UX Designing.webp",
        features: ["Wireframing", "Prototyping", "User Research", "Design Systems"],
      },
      {
        id: 43,
        title: "Pamphlet Designing",
        description: "Effective pamphlet designs for promotions, events, and information distribution.",
        icon: "File",
        reactIcon: "FaFile",
        image: "/image/Brochure Designing.webp",
        features: ["Single & Multi-page", "Eye-catching Designs", "Print Optimization", "Quick Delivery"],
      },
    ],
  },
]

export const serviceCategories = servicesData
